select EMPLOYEE_ID ,JOB_ID ,SALARY ,
	decode(JOB_ID,'AD_VP',SALARY*10,'AD_PRES',SALARY*15,SALARY*2) SALARY2
from EMPLOYEES e 


select * from EMPLOYEES e ;


SELECT EMPNAME,JOBCODE,SALARY,
	DECODE(JOBCODE,'J7',SALARY*1.08,'J6',SALARY*1.07,J5,SALARY*1.05,SALARY*1.03) 인상급여
FROM EMP;


SELECT DEPARTMENT_ID , SUM(SALARY) 합계,FLOOR(AVG(SALARY)) 평균, COUNT(*) 인원수
FROM EMPLOYEES e 
GROUP BY DEPARTMENT_ID 
having AVG(SALARY) > 2800
ORDER BY DEPARTMENT_ID  ASC;;