CREATE TABLE REQ_ACCOUNTS(
       ID NUMBER PRIMARY KEY
     , NICKNAME VARCHAR2(35) UNIQUE
     , EMAIL VARCHAR2(100) UNIQUE
     , ISALLOW CHAR(1) DEFAULT('N') CHECK (ISALLOW IN ('N', 'Y'))
     , REQDATE DATE DEFAULT(SYSDATE)
);

INSERT INTO REQ_ACCOUNTS(ID, NICKNAME, EMAIL)
       VALUES(1, 'hyun', 'abhyuni@gmail.com');

      commit;
      
drop table req_accounts;